pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/giriprasanna7/carwebsite-6521.git'
            }
        }

        stage('Deploy Website') {
            steps {
                sh '''
                chmod +x webserver.sh
                ./webserver.sh
                '''
            }
        }

    }

    post {
        success {
            echo 'Deployment Successful'
        }
        failure {
            echo 'Deployment Failed!'
        }
    }
}
